name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run API/Unit tests (Vitest)
        run: npm run test:api

      # Optional: upload vitest artifacts on failure (if you generate any)
      - name: Upload unit test results (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: |
            test-results/**
            **/junit*.xml
          if-no-files-found: ignore

  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: test-unit
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Cache Playwright browser binaries to speed up CI
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install deps
        run: npm ci

      # Install Playwright browsers and Linux system deps
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Run E2E tests; playwright.config.ts starts the API via `npm run dev:api` on PORT=4000
      - name: Run E2E tests (Playwright)
        env:
          HOST: 0.0.0.0
          PORT: 4000
          NODE_ENV: test
        run: npm run test:e2e

      # Upload Playwright reports on failure for debugging
      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload Playwright blob report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-blob-report
          path: blob-report
          if-no-files-found: ignore
